themes:
  ashys:
    bg: [10, 10, 10, 204] # RGBA format: [R, G, B, A], where A is 0-255 (204 is ~80% opacity)
    fg: [230, 215, 195, 255]
    red: [234, 71, 39, 255]
    green: [72, 233, 152, 255]
    blue: [94, 196, 255, 255]
    yellow: [253, 223, 110, 255]
    magenta: [189, 36, 35, 255]
    orange: [251, 164, 69, 255]
    cyan: [47, 104, 131, 255]
    black: [10, 10, 10, 255]
    white: [230, 215, 195, 255]
    tab_bar:
      background: [10, 10, 10, 204]
      active_tab:
        bg_color: [94, 196, 255, 255]
        fg_color: [21, 21, 21, 255]
      inactive_tab:
        bg_color: [10, 10, 10, 204]
        fg_color: [230, 215, 195, 255]
      new_tab:
        bg_color: [10, 10, 10, 204]
        fg_color: [230, 215, 195, 255]
    pane_frames:
      active:
        bg_color: [94, 196, 255, 255]
        fg_color: [21, 21, 21, 255]
      inactive:
        bg_color: [10, 10, 10, 204]
        fg_color: [230, 215, 195, 255]
    status_bar:
      background: [10, 10, 10, 204]
      text: [230, 215, 195, 255]
      session:
        bg_color: "#5EC4FF"
        fg_color: "#151515"
      mode:
        normal:
          bg_color: "#48E998"
          fg_color: "#151515"
        locked:
          bg_color: "#EA4727"
          fg_color: "#151515"
        resize:
          bg_color: "#FDDF6E"
          fg_color: "#151515"
        pane:
          bg_color: "#2F6883"
          fg_color: "#151515"
        tab:
          bg_color: "#BD2423"
          fg_color: "#151515"
        search:
          bg_color: "#FBA445"
          fg_color: "#151515"
        scroll:
          bg_color: "#34A76F"
          fg_color: "#151515"
        enter_search:
          bg_color: "#FBA445"
          fg_color: "#151515"
        session_select:
          bg_color: "#5EC4FF"
          fg_color: "#151515"
        move:
          bg_color: "#BD2423"
          fg_color: "#151515"
