git_config: ENC[AES256_GCM,data:3v3O9QYAM1G9hqXISy1/sysekbxH5RHGMMuSdDJPnUaIyilmpg+VEmFrbP/xZIfFZEj1RQ5mzeU3jAc/oISR66SzNdFky1yUX5g5UFZcmnm9U7qxK581MvFJtPEVsNu0xmIkCoevcXloiXxnFb42dkf1vMj9kzVriL3ruweWbhMLCOYjcUG/KLING73VoFVoCVXNiq54ZT4mphde3zLJK3QsprsRdL7qiU+zolSjaGI+t/RHbmJxMet9oTzkvDRo2+XzGAFSqcQcvPUjgyUZf5he01OUPk9nZcIPHyANBJsF11M+GydbNBacFX2RrIDmu8lHHtMoqNXyJ7XdJeN0oKfFyWJqTjLItyzpu92eundFbRMICkEmiOnH7Pw5d6OupZV0R7JtA4q5gMSd6ns9/dVWFLBxzcCuVKEE3LFCa2u8AjyYssUCZ/3khNRnKTDwV2qWePGvMisWNT3NgehtfwLMa6Oj3Cc6oknGX/5MXgVJ+2XQIfxULA4NrZ1YtyC1/DK0ZhwiXn0XG9UsXR1fwoggx3AXecD3HWQ8rlNHRIWJZIeTH/1dTl/86y9vSYgbCBPQuWMB+hhP8mPMELW1bc0NkP4hIbIX76nOl1edIiiZETbXwwc4K2iWp/4gHwikEltWsMV8QK8t86zAae0DtZDeyYFk8UEWwluI4SOnrnJux+qOz2mhElHp8YDPDN99Q8E0gO3XJp0uoQuH6G8o/AUzxYL+e0ghHd8YIwdtne/WqE3LbPoLRzj3Qjz3VVZpMNS/5WHV1NlXDM5qGroqiWFtXyEfch0NStz7mBWqUOBtcO2m1wzO1e0vZQiikqspKTdf3Wj/jhycjjYDPaoNmekgOrWkTYY71I6a7QIpNaKva2QghWlfNmAFvlW/sB8A3oD6lmWukXYZiYQKE0chKgSY,iv:VA88MpMuTUq7jBzxKP+nmBZAD+Onb/sgBoct9FbKxYU=,tag:zCtyeFMVn5/vqJFDNfuzxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16e0mm7dknmkqzl469jdrcz3cdr4fx2ej5zndlenmk3g3lfescacsfr3s28
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbDR1cnpCQUo1SG5WYVMz
            eUNNZE9yR3dUTlZsby9FVDJLNUo3QjBFOW5vCm5NWTExQmNLeThwQXpFeXRkb21J
            dWdXOStiUjAzN2JpWWl1NDJyUHpIdzgKLS0tIGZqSkN4SitGS3J6b3ZHVzZHaUd3
            YnBvaFlFVnZodzVvQXRhdzFiam9zcFUKrO6+pWy3IWwd2fJ5tvq1XdGo7mfTCHg3
            hxAA48pVTBONKhO6nN+hCe6YLQRe0DW2qBBtYWws4ju6nG/Y11QLxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-05T20:27:34Z"
    mac: ENC[AES256_GCM,data:w5yVBuuTRDIcWMi/EtSIckVZnIyKR5ni/DD+p9KQdMXW7BWEzPuEczZD5mS62RSkHiPFqdN5A0VKarmi7JA0ZtNTeMvCZfxzQWOvqCvvWVcfZt5rNNbr8DxyGftVwoPKPk1SiXjyyTjdzVc38Rg3M3lBI6WcLhXcMpltG9fIVl0=,iv:7dXeKGFpBa9E7Mlyv3wRx/JlGu8SNKBPunQZbY9IXcQ=,tag:h/iCF3ngmps42p323NZOaw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
