users:
    ay:
        name: ENC[AES256_GCM,data:vynxpvl2,iv:YI0QpW1CKjUbJrKkwuj65Bq9vGoNg/tATryouSRJPYk=,tag:0XTq6ZpJbgyX9pUCkPvHbQ==,type:str]
        email: ENC[AES256_GCM,data:/jOiAHmqszYu8ryxI9NCoteym6e6qtmrCVrE/80Jz+7EsnmDefCpKuY=,iv:HU4krEPdPnaksRyO1Vu+WkE8m21Z1+6BljeoXj3JBBM=,tag:w+pv8qcLxR9vw7X8gbl7rQ==,type:str]
    a0:
        name: ENC[AES256_GCM,data:1brX132wieMfwA==,iv:sxNPZj98oui7AE8MhEVefCw21c0wEF8/xipXjL4XhCE=,tag:gTySJhNpNGpAOMO2CKJ7VA==,type:str]
        email: ENC[AES256_GCM,data:btN3762Sn47uVU9/bRMhZ/94SPETrUl20JG79jsd7f3UNNTYTJVxe2V5909s,iv:7UkkIGEmx/BPmnjqFdyaBSz5ibwWl7v6nruejn0mB+s=,tag:nuQ3spXqXEdaDqCtG05/wQ==,type:str]
    db:
        name: ENC[AES256_GCM,data:j/VHIHM=,iv:awNb7w7MdgREzu+wLYJXheYHrZpbIsq6r00FMinyu/k=,tag:vBGzCoaemcLL8XaK1F7VbA==,type:str]
        email: ENC[AES256_GCM,data:IeiuWz/PW+IV/yeoDqDA/F7ZuZrMUWwa6hUTZQu/XUqkh80xcEHaBg==,iv:NWwhUVp7UKA8aMKYI9HEW7bvX/JcwgqOnJ8RvAOiFVU=,tag:c/hTtDvJzI3KpwmnZK/kTg==,type:str]
includeIf:
    gitdir:~/Developer/ay/:
        path: ENC[AES256_GCM,data:WBglVHugPfcs+hX7GB9x,iv:LAgopwzHFNtcxMSfAg8TBkf5QrtA9lCZUu/yY3rdDEE=,tag:xNNowQChPZqn76L7qwTVMA==,type:str]
    gitdir:~/Developer/a0/:
        path: ENC[AES256_GCM,data:KBSntMUsf8BxSDsHU4BU,iv:bnxMCFIQ9lMgxyFO8wBLL/0diamyuvAJq7gdAG7X67w=,tag:Q2Kd+bY3Wb7E8avHmRWCnQ==,type:str]
    gitdir:~/Developer/db/:
        path: ENC[AES256_GCM,data:ZM7BvptJuRyYB1/oXaN7,iv:/Vnv6T0vi+RY7c8+35pNhNSAijZtVoXIFrJwr7T+FvE=,tag:W8trBa5Lv1lSqfDK09VAUg==,type:str]
url:
    git@github.com:0x616e6f73/:
        pushInsteadOf: ENC[AES256_GCM,data:AjRjza8zBZ3Jib1eggK9javVNfkM1h9CNO/VGz4h,iv:a0zh4GdvNY0sBQ3pTkjjT/7kFvf2Lz24k+y2S9RNkUE=,tag:0ad5WEeXN8Q+iuiAIDUgxg==,type:str]
    git@github.com:deyba/:
        pushInsteadOf: ENC[AES256_GCM,data:zhkHaGS0I6LKAkJA1DmqbvCpLmgWi8QTWw==,iv:uqqwGJ38g4oL98GaI3VIUIpjqaoI6ZahfIi1ikwVXj0=,tag:e7u5XJf+EYikJhqP0T/wZQ==,type:str]
    git@github.com:ay-mxn/:
        pushInsteadOf: ENC[AES256_GCM,data:IUJfikEErGOk2iQSvc8mkDatizgwklvq9z0=,iv:HPYAl2UQasXBrggBgydbM3mk/GmBlLbPXFicchzmOl0=,tag:0pKNEN+cEzJGkuCZ3gWliQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16e0mm7dknmkqzl469jdrcz3cdr4fx2ej5zndlenmk3g3lfescacsfr3s28
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbDR1cnpCQUo1SG5WYVMz
            eUNNZE9yR3dUTlZsby9FVDJLNUo3QjBFOW5vCm5NWTExQmNLeThwQXpFeXRkb21J
            dWdXOStiUjAzN2JpWWl1NDJyUHpIdzgKLS0tIGZqSkN4SitGS3J6b3ZHVzZHaUd3
            YnBvaFlFVnZodzVvQXRhdzFiam9zcFUKrO6+pWy3IWwd2fJ5tvq1XdGo7mfTCHg3
            hxAA48pVTBONKhO6nN+hCe6YLQRe0DW2qBBtYWws4ju6nG/Y11QLxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T19:37:32Z"
    mac: ENC[AES256_GCM,data:+7L/2ri3BZlG+gN3Az+5WnqK3lqf0ps1UlSnQpWwc+AlhEQKBbBgZ8892+VzU8uq4ZWpJLo73+lQ5hteby8Guhj8/yaniAs5JsgTi0wg8ilsbIagHKA9L0BolpB5ml4VcCmnYYH1112bmyoa3hfCAUctZI0xaOfGu8Lp/hAZk6Y=,iv:fDKfb3sOM7OSZImutp1QLQvGWJVR3P+nM7FhJTm+2tQ=,tag:+lcAkmo0YW4omerpzMNIXA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
